on:
  push:
    branches-ignore:
      - master
  pull_request:
    types: [reopened, opened, synchronize, edited]

name: Create PR Env
jobs:
  create_env:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      ENV_PREFIX: '${{ github.head_ref }}.'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set env
        run: echo "::set-env name=BRANCH_NAME::$(git symbolic-ref --short HEAD)"
        #run: echo "::set-env name=BRANCH_NAME::$(git name-rev --no-undefined --name-only HEAD)"
      - name: Print env
        run: echo $ENV_PREFIX
#      - name: Install Dependencies
#        run: yarn
#      - name: Build Site
#        run: yarn build
#      - name: 'Terraform Init'
#        uses: hashicorp/terraform-github-actions@master
#        with:
#          tf_actions_version: 0.12.13
#          tf_actions_subcommand: 'init'
#          args: '-backend-config="key=${{ env.ENV_PREFIX }}jkrsp.com.tfstate"'
#      - name: 'Terraform Plan'
#        uses: hashicorp/terraform-github-actions@master
#        with:
#          tf_actions_version: 0.12.13
#          tf_actions_subcommand: 'plan'
#          args: '-var="is_temp_env=true" -var="env_prefix=${{ env.ENV_PREFIX }}" -out tf.plan'
#      - name: 'Terraform Apply'
#        uses: hashicorp/terraform-github-actions@master
#        with:
#          tf_actions_version: 0.12.13
#          tf_actions_subcommand: 'apply'
#          args: 'tf.plan'
#      - name: 'Terraform Output'
#        id: terraform
#        uses: hashicorp/terraform-github-actions@master
#        with:
#          tf_actions_version: 0.12.13
#          tf_actions_subcommand: 'output'
#          args: 'website'
#      - name: 'Use Terraform Output'
#        run: echo ${{ steps.terraform.outputs.tf_actions_output }} | sed "s/\"//g"
#      - name: Display Website link on PR
#        uses: unsplash/comment-on-pr@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          message: "[Review website here](http://${{ steps.terraform.outputs.tf_actions_output }})"
#