on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

name: Create PR Env
jobs:
  create_or_update_pr_env:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build Site
        run: bun run build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: terraform init -backend-config="key=${{ env.BRANCH_NAME }}.jkrsp.com.tfstate"

      - name: Terraform Plan
        run: terraform plan -var="is_temp_env=true" -var="env_prefix=${{ env.BRANCH_NAME }}." -out tf.plan

      - name: Terraform Apply
        run: terraform apply tf.plan

      - name: Terraform Output
        id: terraform
        run: echo "website=$(terraform output -raw website)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Sync to S3
        run: aws s3 sync dist s3://${{ env.BRANCH_NAME }}.jkrsp.com

      - name: Add PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `[Review website here](${process.env.WEBSITE_LINK})`
            })
        env:
          WEBSITE_LINK: ${{ steps.terraform.outputs.website }}

