on:
  push:
    branches-ignore:
      - master
name: Deploy Gatsby Site
jobs:
  env_vars:
    runs-on: ubuntu-latest
    env:
      BUCKET: my-regular-bucket'
    steps:
    - name: set env vars
      run: export BUCKET=my-unregular-bucket
    - name: print env vars
      run: echo $BUCKET
